### ISSUE TITLE
[Request] Auto-redeem rewards when a player receives one / on the RewardCheck time

### ISSUE THREAD

**Issue by I-Knight-I** [NathanCollaert/RewardsLite#3]
It's a little tedious having to constantly do /redeemrewards. It'd be useful if player's would simply just receive their reward - if they are eligible - every time the RewardCheck time is met. 

E.g 

> RewardCheck: 60
> AutoRedeem: True

`if (player.eligible() == true){`
`    player.redeem()`
`}`

**Comment by NathanCollaert** [comment]
As of right now, players do actually redeem it automatically after every check. Although the players will have to wait for the check timer to actually hit 0, which I didn't like as well but had no other option due to my implementation at that time.
I've been working on a new custom playtime system that will allow me to get rid of the whole rewardCheck setting and give players their reward on the exact time it was achieved.

**Comment by I-Knight-I** [comment]
Yeah I actually noticed a few hours after opening this that it was automatic, apologies. 

I saw you begun editing the system too. I downloaded the source and wondered what the heck was happening when everything was commented out lol. I look forward to the rewritten version.

**Comment by NathanCollaert** [comment]
I should probably start working with branches ya haha
