### ISSUE TITLE
In-game playtime vs userdata playtime vs reward playtime issues.

### ISSUE THREAD

**Issue by CallistoMC55** [NathanCollaert/RewardsLite#32]
**So, in the rewards.yml file I have the "Well known" rank set to be 1200 minutes (20 hours) I have it set in this image @ 650 mins to test**
 
![SC3](https://user-images.githubusercontent.com/109365083/179259972-7b78217d-6186-4925-b51c-ffa632c295ce.png)

**In game, I have 23 hours+**
 
![SC1](https://user-images.githubusercontent.com/109365083/179260178-3e0aee15-1a80-4a65-9169-cfafdefe03cc.png)

**For some reason, when I am looking at rewards in game, the remaining time to get the reward is 4 hours?**

![SC4](https://user-images.githubusercontent.com/109365083/179260797-0650545d-e74b-42e4-b7c7-998c8e3e350b.png)

**When looking at the player data I am unsure what the format the values are in.** 
![SC2](https://user-images.githubusercontent.com/109365083/179261060-e120b27f-88b7-4b6a-85ad-52d026b0ec1c.png)
![SC5](https://user-images.githubusercontent.com/109365083/179261406-233273b1-2ac1-4bc1-84f8-e99f77c1a663.png)

**Comment by NathanCollaert** [comment]
Hi there, is it possible that you have set the "well known" rank to 4 hours in the past?

Currently LPR does not refresh timeTillNextReward if a reward required time has been altered. E.g. if you set a reward to require 4 hours and log in as player, then alter the reward to require 2 hours. The reward for the players who had already logged in when the reward was 4 hours will still be 4 hours until the reward has been claimed or it has been removed from their userdata.

This bug has been fixed in the complete overhaul of LPR which will be released this weekend!

**Comment by CallistoMC55** [comment]
Hey! So, does that mean if I reset the userdata then reimplement the rewards.yml with the correct amounts of time it should fix the issue?

If not I can just wait for the update :)

thanks for the help!

**Comment by NathanCollaert** [comment]
If you set the reward in the rewards.yml to 2 hours and then reset the userdata it should fix itself yes.

**Comment by CallistoMC55** [comment]
Awesome! I got it all fixed. Thanks!
