### ISSUE TITLE
How to setup multiple rewards

### ISSUE THREAD

**Issue by KapsiF** [NathanCollaert/RewardsLite#34]
I currently have no rewards.yml
I only have the these

![image](https://user-images.githubusercontent.com/73310940/183747009-e9dbcdc3-868f-4730-90c2-9fdbea2e38cc.png)

**Comment by NathanCollaert** [comment]
Hi there, since RewardsLite v3.0.0 the rewards.yml file is not used anymore. I haven't had time yet to update the wiki (hence the outdated warning at the top).
Creating a new reward is as easy as copying over the file contents of the default-reward.yml (**except for the generated section**) to a new file and alter the configurations accordingly. That's all!

**Comment by KapsiF** [comment]
Okay thank you!
